### ISSUE TITLE
Music Bar is shown in Mission Control

### ISSUE THREAD

**Issue by petebocken** [musa11971/Music-Bar#32] opened 2020-01-08 12:53 UTC
The app is shown in Mission Control and it should not be since it is just a menu bar app. In Mission Control, you can see just the app name "Music Bar".

https://p110.p2.n0.cdn.getcloudapp.com/items/d5ueNXzb/Screen+Shot+2020-01-08+at+6.52.16+AM.png?v=f63fd6c18a679461bcfdfa1ca5fb9e02

**Comment by musa11971** [comment] 2020-01-09 18:12
For me, this only happens when I have the Music Bar popover opened and then open Mission Control (which is intended behavior).

Does this always happen for you? Do you have any additional information that could help identify the issue?

Thanks.

**Comment by petebocken** [comment] 2020-01-09 19:21
It displays just the app name text when MusicBar is closed and displays both the menu and text when it's open (as expected).

Here is a screen recording: https://p110.p2.n0.cdn.getcloudapp.com/items/bLuGK7jq/Screen+Recording+2020-01-09+at+01.19+PM.mov

MusicBar 1.3
macOS 10.15.2

Let me know what other details I can provide to help.

**Comment by musa11971** [comment] 2020-12-10 12:07
Fixed in #49

**Closed by musa11971** 2020-12-10 12:07 UTC
Labels: help wanted, needs more info
